# Generated by Django 2.2.2 on 2019-07-15 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=100)),
                ('priority', models.IntegerField()),
                ('method', models.CharField(max_length=200, null=True)),
                ('operator_name', models.CharField(max_length=20, null=True)),
                ('inspector_name', models.CharField(max_length=20, null=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('deal_date', models.DateTimeField(verbose_name='date handled')),
                ('state', models.IntegerField()),
                ('detail_state', models.CharField(max_length=10)),
                ('deal_addition', models.CharField(max_length=300, null=True)),
                ('deal_info', models.CharField(max_length=300, null=True)),
                ('test_info', models.CharField(max_length=300, null=True)),
                ('test_addition', models.CharField(max_length=300, null=True)),
                ('note', models.CharField(max_length=300, null=True)),
                ('judge', models.CharField(max_length=5)),
                ('result', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('detail', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100)),
                ('authority', models.IntegerField()),
                ('tel_number', models.CharField(max_length=20, null=True)),
                ('E_mail', models.CharField(max_length=100, null=True)),
                ('sex', models.CharField(max_length=4, null=True)),
                ('note', models.CharField(max_length=500, null=True)),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userManage.Module')),
            ],
        ),
        migrations.CreateModel(
            name='UnassignedEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userManage.Event')),
            ],
        ),
        migrations.CreateModel(
            name='SolvedEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userManage.Event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_inspector', to='userManage.Users'),
        ),
        migrations.AddField(
            model_name='event',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userManage.Module'),
        ),
        migrations.AddField(
            model_name='event',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_operator', to='userManage.Users'),
        ),
        migrations.CreateModel(
            name='CurrentEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userManage.Event')),
            ],
        ),
    ]
