# Generated by Django 2.2.2 on 2019-07-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('authority', models.IntegerField()),
                ('tel_number', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
