# Generated by Django 2.2.2 on 2019-07-11 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userManage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='users',
            old_name='address',
            new_name='E_mail',
        ),
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='sex',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='operate_module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userManage.Module'),
        ),
    ]
