# Generated by Django 2.2.2 on 2019-07-15 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentevent',
            name='foreign_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solvedevent',
            name='foreign_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unassignedevent',
            name='foreign_id',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
