# Generated by Django 2.2.2 on 2019-07-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManage', '0002_auto_20190715_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
