# Generated by Django 2.2.2 on 2019-07-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManage', '0002_auto_20190711_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='note',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
