# Generated by Django 2.2.2 on 2019-07-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManage', '0003_users_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='detail',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
