# Generated by Django 2.2.2 on 2019-07-11 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userManage', '0004_auto_20190711_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=100)),
                ('priority', models.IntegerField()),
                ('method', models.CharField(max_length=200)),
                ('operator_name', models.CharField(max_length=20)),
                ('inspector_name', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('deal_date', models.DateTimeField(verbose_name='date handled')),
                ('state', models.IntegerField()),
                ('detail_state', models.IntegerField()),
                ('operator_addition', models.CharField(max_length=300)),
                ('test_info', models.CharField(max_length=300)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userManage.Module')),
            ],
        ),
    ]
