# Generated by Django 2.2.2 on 2019-07-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManage', '0005_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='inspector_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='method',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='operator_addition',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='operator_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='test_info',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
